- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_v3_0429_en_02_shard_SRC_fromdialogue_interruption0.5/train

- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_v3_0429_en_02_shard_SRC_fromdialogue_interruption0/train

- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_ToD_spokenwoz_fixcot_small_filtered_interruption0.5/train

- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_ToD_spokenwoz_fixcot_small_filtered_interruption0/train

- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_llama_q_fixcot_small_filtered_interruption0.5/train

- type: group
  weight: 1.0
  tags:
    s2s_duplex: true
  input_cfg:
    - type: lhotse_shar
      shar_path: /mnt/donghang-jfs/duplex/shard_llama_q_fixcot_small_filtered_interruption0/train

# - type: group
#   weight: 1.0
#   tags:
#     s2s_duplex: true
#   input_cfg:
#     - type: lhotse_shar
#       shar_path: /mnt/donghang-jfs/duplex/shard_uro_mt_fixcot_small_filtered_interruption0.5/train

# - type: group
#   weight: 1.0
#   tags:
#     s2s_duplex: true
#   input_cfg:
#     - type: lhotse_shar
#       shar_path: /mnt/donghang-jfs/duplex/shard_uro_mt_fixcot_small_filtered_interruption0/train
